// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'remove-button': string;
  'removeButton': string;
  'story': string;
}
declare var cssExports: CssExports;
export = cssExports;
